### PR TITLE
Improve subtitle for tasks in task list to be more informative of the actual time

### LINKED ISSUE #265: Improve "time remaining" part of task list
## Description

If a task is set to expire less than 24 hours from now, the task list still reports that there are "1 days remaining" as seen in the screenshots below. The suggestion is to make this more granular (i.e "humanize" it by showing a more specific time unit)

## Screenshots

image

### PR DESCRIPTION
**Pull request by SlimShadyIAm**
This PR adds a util in the form of an extension to the `Duration` class called `humanize`. 

Previously, the task list only showed the time remaining in the form of days. Now, it handles:
- seconds
- minutes
- hours
- days

flutter_10

Time unit strings have been translated for Danish and Spanish as well. It also takes into account pluralization.

Closes #265.

### CODE REVIEW

**Review by LarsRefsgaard — APPROVED** [review]

**Review by Panosfunk — COMMENTED** [review]
What does '2 min to complete - 17 hours remaining' mean?

Is the first one estimated time of completion and the second one is time remaining before the task expires?

**Comment by SlimShadyIAm** [comment]
Yes, and that's how it currently was anyway. But I agree it could be made more clear.

> Expires in 17 hours

would that be more clear?

**Comment by Panosfunk** [comment]
> Yes, and that's how it currently was anyway. But I agree it could be made more clear.
> 
> > Expires in 17 hours
> 
> would that be more clear?

Yes, something like:

est time: 2 mins
Expires in: 17 hours

I think it would help the users understand better

**Comment by SlimShadyIAm** [comment]
Looking into how this card can be redesigned.

**Pull request merged**
