### PR TITLE
Switching studies on the study app does not fully work

### PR DESCRIPTION
**Pull request by bardram**
* fix of #283 including update of UI views accordingly (e.g. updating the list of data viz cards)
* upgrade to the latest versions of the CAMS package (which solves most of issue #283)
* [Aligning iOS "marketing version" with Flutter pubspec version](https://github.com/cph-cachet/carp_studies_app/commit/5c347c8b5c3c56f7678548c31c621439bdb56378)
* improvement to some Danish translations
* refactor of "check connectivity" function

### CODE REVIEW

**Comment by bardram** [comment]
OneTimeTrigger are not triggered in the Demo protocol.

```
[log] [CAMS INFO] Initializing OneTimeTriggerExecutor [423822601] (created)
[log] [CAMS INFO] Initializing OneTimeTriggerExecutor [165194854] (created)
[log] [CAMS INFO] Initializing OneTimeTriggerExecutor [943096521] (created)
[log] [CAMS INFO] Initializing OneTimeTriggerExecutor [214433811] (created)
[log] [CAMS INFO] Initializing OneTimeTriggerExecutor [942876187] (created)
[log] [CAMS INFO] Initializing OneTimeTriggerExecutor [394780632] (created)
[log] [CAMS INFO] Starting OneTimeTriggerExecutor [423822601] (initialized)
[log] [CAMS INFO] Starting OneTimeTriggerExecutor [165194854] (initialized)
[log] [CAMS INFO] Starting OneTimeTriggerExecutor [943096521] (initialized)
[log] [CAMS INFO] Starting OneTimeTriggerExecutor [214433811] (initialized)
[log] [CAMS INFO] Starting OneTimeTriggerExecutor [942876187] (initialized)
[log] [CAMS INFO] Starting OneTimeTriggerExecutor [394780632] (initialized)
2
[log] [CAMS WARNING] OneTimeTriggerExecutor - one time trigger already occurred at: 2024-05-06 11:09:46.461983. Will not trigger now.
2
[log] [CAMS WARNING] OneTimeTriggerExecutor - one time trigger already occurred at: 2024-05-06 11:09:46.461983. Will not trigger now.
[log] [CAMS WARNING] OneTimeTriggerExecutor - one time trigger already occurred at: 2024-05-06 11:09:46.461983. Will not trigger now.
```

**Comment by bardram** [comment]
> OneTimeTriggers are not triggered in the Demo protocol => only the `Enviromemt` task is shown.

This is an issue with CAWS or CARP Core - see https://github.com/cph-cachet/carp-webservices-spring/issues/56

**Comment by bardram** [comment]
I've released version 1.6.1 of CAMS which handles this situation (where the Triggers are reduced by CARP Core).

**Comment by bardram** [comment]
I've released version 1.6.1 of CAMS which handles this situation (where the Triggers are reduced by CARP Core).

**Comment by SlimShadyIAm** [comment]
With the latest CAMS it does not seem to ask for location permissions, and consequently it does not show up as connected:

image

**Comment by SlimShadyIAm** [comment]
I also have an issue where for a specific study, after accepting an invitation I see a spinner and it just gets stuck there with no errors in the console.

I've invited you to the study it happens in, called "SLEEPINESS Test (leaving study)", and here is the protocol:

[SLEEPINESS - phase 1 [dev].json](https://github.com/cph-cachet/carp_studies_app/files/15263143/SLEEPINESS.-.phase.1.dev.json)

**Comment by bardram** [comment]
> With the latest CAMS it does not seem to ask for location permissions, and consequently it does not show up as connected:
> 


This should have been fixed.

**Comment by bardram** [comment]
> I also have an issue where for a specific study, after accepting an invitation I see a spinner and it just gets stuck there with no errors in the console.
> 
> I've invited you to the study it happens in, called "SLEEPINESS Test (leaving study)", and here is the protocol:
> 

As far as I can see, this is because the informed consent you have attached to this study is a JSON that contains the protocol, and not the informed consent JSON..... This makes the parsing of the JSON fail and the app gets stuck in this. I will try to catch this error and handle it so that the app doesn't get stuck.

**Comment by bardram** [comment]
> > I also have an issue where for a specific study, after accepting an invitation I see a spinner and it just gets stuck there with no errors in the console.
> > I've invited you to the study it happens in, called "SLEEPINESS Test (leaving study)", and here is the protocol:
> 
> As far as I can see, this is because the informed consent you have attached to this study is a JSON that contains the protocol, and not the informed consent JSON..... This makes the parsing of the JSON fail and the app gets stuck in this. I will try to catch this error and handle it so that the app doesn't get stuck.

I've now added error handling of this situation, and the app now issues a warning if it can parse the JSON as a proper informed consent:

```
[log] [CAMS WARNING] CarpResourceManager - Error parsing informed consent - SerializationException - A 'fromJson' function was not found in the FromJsonFactory for the type 'null'. Register a Serializable class using the 'FromJsonFactory().register()' method.
If you are using CARP Mobile Sensing, you can ensure json initialization by calling'CarpMobileSensing.ensureInitialized()' as part of your main method.
``` 

A new version of `carp_backend` with this has been published.

**Pull request merged**
